---
require: rubocop-rspec

AllCops:
  NewCops: enable
  Exclude:
  - 'build/**/*'
Layout/EmptyLinesAroundBlockBody:
  Exclude:
  - 'spec/**/*.rb'
Layout/EmptyLinesAroundClassBody:
  Enabled: false
Layout/EmptyLinesAroundModuleBody:
  Enabled: false
Layout/LineLength:
  Max: 120
Layout/MultilineOperationIndentation:
  Enabled: false
Metrics/AbcSize:
 Max: 25
Metrics/BlockLength:
  Exclude:
  - 'spec/**/*.rb'
Metrics/ClassLength:
  Max: 250
Metrics/CyclomaticComplexity:
  Max: 10
Metrics/MethodLength:
  Max: 25
Naming/MethodParameterName:
  Enabled: false
Metrics/ParameterLists:
  Max: 10
Metrics/PerceivedComplexity:
  Max: 10
RSpec/AnyInstance:
  Enabled: false
RSpec/ExampleLength:
  Max: 20
RSpec/ExpectOutput:
  Enabled: false
RSpec/FilePath:
  Enabled: false
RSpec/MissingExampleGroupArgument:
  Enabled: false
RSpec/MultipleExpectations:
  Enabled: false
RSpec/NestedGroups:
  Max: 4
Security/Open:
  Enabled: false # False positive at the moment
Style/Documentation:
  Enabled: false
Style/FormatStringToken:
  Enabled: false
Style/MethodMissingSuper:
  Enabled: false
